### ISSUE TITLE
剧情翻译的一点小问题

### ISSUE THREAD

**Issue by Mark9804** [ba-archive/ba-online-toolbox#9]
1. 日语原文不需要使用 input，没有需要更改日语的需求

<img width="184" alt="image" src="https://user-images.githubusercontent.com/9006264/222495379-023f37bc-276e-483b-ae9a-5e6fe5592321.png">

2. momotalk 翻译的输入框我并没有用 naive-ui 而是自己实现了一个，因为当使用辅助翻译工具改变文本内容（比如momotalk翻译工具中的“接受机翻”行为）时，naive-ui 的 input 组件并不会动态更新文本（element-plus 可以）

3. 我们之后的剧情入点是 `content`，不再是直接读取 json 序列。可以参考 https://yuuka.diyigemt.com/story/vol3/31010.json
<img width="309" alt="image" src="https://user-images.githubusercontent.com/9006264/222496012-b197a1a7-f0fa-4106-80ed-c6db17c68d62.png">

5. `[框内文本]`的内容处理，我目前有两种思路

一种是 ba-story-player 的正则匹配

https://github.com/ba-archive/ba-story-player/blob/ba863e9a80f77589ecf6d82002586a12544f45c1/lib/layers/translationLayer/utils.ts#L61-L85

一种是搓一个 AST

https://github.com/ba-archive/ba-online-toolbox/blob/83c633b5e6a060d936d0e2ced27ba59520d7852e/src/tools/AronaTalk/utils/ChatContentCompiler.ts#L4-L228

（我这个实现循环次数有点多，有点小小的性能问题，不确定单元多了会怎么样，但我选择相信摩尔定律）

**Comment by ShinonomeSetsuna** [comment]
1. 日语原文使用的是placeholder, 不清楚其他设备怎么样我这边是根本无法修改的, 使用input只是因为觉得这个ui看起来好看一点(x
2. 这个问题我打算使用在调用翻译的时候使用其他函数进行更新, 如果实现比较麻烦会考虑重新手写input
3. 已修改(好久没看项目没注意到格式修改了
5. 因为这只是一个翻译的GUI所以使用了非常古朴的方法进行处理...不过应该没问题.
